name: Check health of signalling protocol

on:
  workflow_dispatch:
  push:
    paths:
      - "Common/**"
      - "Signalling/**"
      - "SignallingWebServer/**"
      - "SS_Test/**"
  pull_request:
    paths:
      - "Common/**"
      - "Signalling/**"
      - "SignallingWebServer/**"
      - "SS_Test/**"

jobs:
  signalling-protocol-test:
    if: github.repository == 'EpicGamesExt/PixelStreamingInfrastructure'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
        
    - name: Launch signalling tests in docker containers
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "SS_Test/docker-compose.yml"
        up-flags: "--build --abort-on-container-exit --exit-code-from tester"

